# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bratislava' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bratislava
  pod 'RNMobileCenter', '~> 0.5.0'
  pod 'MobileCenter', '~> 0.9.0'

  

  target 'bratislavaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'bratislava-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bratislava-tvOS

  target 'bratislava-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
